name: ci/dev-check
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js (if you need it)
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Run a placeholder step
        run: 'echo "ci/dev-check: all good"'

